### ISSUE TITLE
NFT decreaseLiquidity should be supported

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giv-token-subgraph#18]
In case the user collects its NFT we don't remove it from UI!
Probably supporting the decrease liquidity event will solve this issue. Consequently, increase liquidity support will be needed.

**Comment by aminlatifi** [comment]
Tx like this has removed the liquidity
https://etherscan.io/tx/0xfc2e90e156b9a807915a5d6e1652603dfc6182154229a5185439b31a065a64f7#eventlog

**Comment by mohammadranjbarz** [comment]
It's ok, you can test it here ( please tell me if it was ok, I can apply these changes on  `mainent` branch

https://liquidity-mining-dapp.vercel.app/givfarm

**Comment by mohammadranjbarz** [comment]
<img width="1440" alt="Screen Shot 1400-10-06 at 12 05 50" src="https://user-images.githubusercontent.com/9850545/147452610-bb3756db-f382-4463-b67e-6f5551ee5c49.png">
Now I have two NFT, one of them has been removed, I think we should make some changes in frontend for these cases


And this is my NFTs on uniswap

<img width="893" alt="Screen Shot 1400-10-06 at 12 16 35" src="https://user-images.githubusercontent.com/9850545/147453608-5044708d-927a-4fdc-8a55-92cd84985383.png">
