### ISSUE TITLE
Add LP staked/unstaked balance support to subgraph

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giv-token-subgraph#2]
- [x] BalancerLP
- [x] BalancerLPStaked
- [x] SushiswapLP
- [x] SushiswapLPStaked
- [x] HoneyswapLP
- [x] HoneyswapLPStaked
- [x] GivStaked

**Comment by mohammadranjbarz** [comment]
> * [ ]  BalancerLP
> * [ ]  BalancerLPStaked
> * [ ]  SushiswapLP
> * [ ]  SushiswapLPStaked
> * [ ]  HoneyswapLP
> * [ ]  HoneyswapLPStaked
> * [ ]  GivStaked

Could you please give me the contract addresses and tell me how can I access the ABIs for any of these contracts?

**Comment by mohammadranjbarz** [comment]
* LM (Unipool):
    * stake
    * unstak or wihtdraw
* LP (ERC20 ABI) :
    * Transfer  ( just put this event in ABI, not needed other events or functions)

- [x] BalancerLP (Kovan)(0x1ee71e1ed744ae6d4058f5c7797c2e583dbfb095), just calculate balance ( dont care about stake)
- [x] BalancerLPStaked ( Process stake event on LM)
- [x] SushiswapLP (XDAI) ( 0x8c77ba1d90c57d584aeed57bc9b55258b8be3438)
- [x] SushiswapLPStaked 
- [x] HoneyswapLP (XDAI)(0xc81c327f43eC566E14C64AedE5DCf5d9c120D5eb)
- [x] HoneyswapLPStaked
- [x] GivStaked (XDAI: 0x26F033515ce926658def0939A8D9a0592D0F5cc9) (KOVAN:0x1aAA619b066360C22EBD8c597c975CACff146317)
