### ISSUE TITLE
Investigate Hosting Subgraph on Our servers

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giv-token-subgraph#48]
Subgraph platform is not reliable, especially on xDai.
It's worth investigating whether it's possible to host a server ourselves and deploy our subgraph instances on it.

For more information follow this message
https://canary.discord.com/channels/@me/953879111120609330/959051719965306890

**Comment by motoraif** [comment]
It can be done using Docker. I will explore the options that we have and give a detailed reply. 

https://github.com/graphprotocol/graph-node/tree/master/docker

**Comment by aminlatifi** [comment]
The subgraph own hosts have been available pretty well recently. So far, let's ignore this issue.
