### ISSUE TITLE
Setup CI/CD for staging and production environment

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giv-token-subgraph#51]
I did something a few monthes ago but for some reason ( like our branchs weren't stable I commented them) but I think it's time to setting  up CI/CD again to prevent inconsistent deployments and human errors

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @MoeNick 

I think it can be a good task for MoeShehab

**Comment by aminlatifi** [comment]
Well done @mohammadranjbarz
